// import NavbarComponent from "@/components/NavbarComponent";
// import SidebarComponent from "@/components/SidebarComponent";

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//     return (
//         <html lang="en">
//             <body className="font-SFProDisplay">

//                 <div className="grid grid-cols-5  grid-flow-row  w-full h-screen gap-8  ">

//                     <div className="">
//                         {/* <SidebarComponent /> */}
//                         <SidebarComponent/>
//                     </div>
//                     <div className="col-span-4 ">


//                         <div className="">
//                             {/* <NavbarComponent /> */}
//                             <NavbarComponent/>
//                         </div>
//                     </div>

//                     {children}
//                     </div>
//             </body>
//         </html>
//     );
// }